version: "3.3"

services:
  traefik:
    image: "traefik"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  my-service:
    image: traefik/whoami
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.my-router.rule=Host(`localhost`)"
      - "traefik.http.routers.my-router.entrypoints=web"
      # Enables digests authentication; use htdigest to generate the passwords.
      - "traefik.http.routers.my-router.middlewares=my-auth"
      # Username: mert 
      # Realm: traefik
      # Password: mert
      - "traefik.http.middlewares.my-auth.digestauth.users=mert:traefik:05eccdeda94d284d63ef8eed837d55c6" 