version: "3.3"

services:
  traefik:
    image: "traefik"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  my-service:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-router.rule=Host(`localhost`)"
      - "traefik.http.routers.my-router.entrypoints=web"
      # Adds IP whitelist middleware
      - "traefik.http.routers.my-router.middlewares=my-allowedlist"
      # Accepts request from specific ip address
      - "traefik.http.middlewares.my-allowedlist.ipwhitelist.sourcerange=172.29.0.1"