version: "3.3"

services:
  traefik:
    image: "traefik"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  my-service:
    image: traefik/whoami
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.my-router.rule=Host(`localhost`)"
      - "traefik.http.routers.my-router.entrypoints=web"
      # Adds rate limit middleware
      - "traefik.http.routers.my-router.middlewares=my-limit"
      # Allows 2 reqs in 5 seconds
      - "traefik.http.middlewares.my-limit.ratelimit.average=2"
      - "traefik.http.middlewares.my-limit.ratelimit.period=5s"