version: "3.3"

services:
  traefik:
    image: "traefik"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  my-service:
    image: traefik/whoami
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.my-router.rule=Host(`localhost`)"
      - "traefik.http.routers.my-router.entrypoints=web"
      # Adds redirect regex middleware
      - "traefik.http.routers.my-router.middlewares=my-redirect"
      # Redirects with domain replacement, http://localhost to https://doc.traefik.io/middlewares
      - "traefik.http.middlewares.my-redirect.redirectregex.regex=^http://localhost/(.*)"
      - "traefik.http.middlewares.my-redirect.redirectregex.replacement=https://doc.traefik.io/traefik/middlewares/$${1}"