version: "3.3"

services:
  traefik:
    image: "traefik"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  my-service:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-router.rule=Host(`localhost`)"
      - "traefik.http.routers.my-router.entrypoints=web"
      # Adds strip prefix middleware
      - "traefik.http.routers.my-router.middlewares=my-prefix"
      # Strips the prefix /v1
      - "traefik.http.middlewares.my-prefix.stripprefix.prefixes=/v1"
      # Ensures the resulting stripped path is not the empty string, by replacing it with / when necessary.
      - "traefik.http.middlewares.my-prefix.stripprefix.forceSlash=true"